const data = {
  wedding: [
    {
      programName: 'Wedding',
      programDate: '2024-01-28T08:00:00',
      programDetails: {
        negara: 'Indonesia',
        waktu: '08:00 - 21:00',
        gedung: 'Masjid Istiqomah',
        jalan: 'Jl. Veteran No. 21 Cisereh',
        desa: 'Kadu Jaya',
        kecamatan: 'Curug',
        kabupaten: 'Tangerang',
        provinsi: 'Banten',
      },
      commitDate: '2024-01-27T08:00:00',
      commitDetails: {
        negara: 'Indonesia',
        waktu: '08:00 - 10:00',
        gedung: 'Rumah Bapak Andy',
        jalan: 'Jl. Veteran No. 22 Cisereh',
        desa: 'Kadu Jaya',
        kecamatan: 'Curug',
        kabupaten: 'Tangerang',
        provinsi: 'Banten',
      },
      partyDate: '2024-01-26T09:00:00',
      partyDetails: {
        negara: 'Indonesia',
        waktu: '09:00 - 12:00',
        gedung: 'Rumah Bapak Fikri',
        jalan: 'Jalan Raya Serang Bitung',
        desa: 'Kadu Jaya',
        kecamatan: 'Curug',
        kabupaten: 'Tangerang',
        provinsi: 'Banten',
      },
      groom: ['Romeo', 'Adam'],
      bride: ['Juliet', 'Hawa'],
      fatherGroom: 'Andy Adam',
      motherGroom: 'Asih Adam',
      fatherBride: 'Fikri Hawa',
      motherBride: 'Yuli Hawa',
      gifts: {
        gift1: 64248890,
        nameGift1: 'Adam',
        bankGift1: 'BCA',
        gift2: 64248891,
        nameGift2: 'Hawa',
        bankGift2: 'BCA',
        gift3: 64248892,
        nameGift3: 'Adam & Hawa',
        bankGift3: 'BCA',
        gift4: '',
        nameGift4: '',
        bankGift4: '',
      },
      guests: [
        {
          name: 'Anya',
          from: 'Tangerang',
          phone: '081987654320',
          occupation: 'Family Adam',
          status: 'Vip',
          message: 'Selamat menikah',
        },
        {
          name: 'Reza',
          from: 'Jakarta',
          phone: '081987654321',
          occupation: 'Family Hawa',
          status: 'Vip',
          message: 'Selamat menikah',
        },
        {
          name: 'Jacob',
          from: 'Bekasi',
          phone: '081987654322',
          occupation: 'Atasan Kerja',
          status: 'Vip',
          message: 'Selamat menikah',
        },
        {
          name: 'Ratih',
          from: 'Bogor',
          phone: '081987654323',
          occupation: 'Teman',
          status: '',
          message: 'Selamat menikah',
        },
        {
          name: 'Rian',
          from: 'Jakarta',
          phone: '081987654324',
          occupation: 'Tetangga',
          status: '',
          message: 'Selamat menikah',
        },
      ],
      imageGroom: 'imageGroom.jpg',
      urlImageGroom: 'http://localhost:3002/assets/groomImage.jpg',
      imageBride: 'imageBride.jpg',
      urlImageBride: 'http://localhost:3002/assets/brideImage.jpg',
      video: 'videoWdding.mp4',
      urlVideo: 'http://localhost:3002/assets/videoWedding.mp4',
    },
  ],
};
export default data;
